### ISSUE TITLE
RKBridgeModulePhoneDelegate 代理touchDown touchUp不成对出现

### ISSUE THREAD

**Issue by weipinglii** [Rokid/RokidMobileSDKiOSDemo#10]
- RKBridgeModulePhoneDelegate 代理touchDown touchUp不成对出现, touchUp事件几乎不会被响应

- touchMove事件从来没有响应过

**麻烦更新的内容要在DEMO里面测试过OK之后再发布出来**
**麻烦更新的内容要在DEMO里面测试过OK之后再发布出来**
**麻烦更新的内容要在DEMO里面测试过OK之后再发布出来**

不然浪费很多彼此的时间和精力 #9

**Comment by shper** [comment]
SDK Bridge 只负责 暴露 touch 接口，具体调用 要看 H5 页面的使用。

**Comment by weipinglii** [comment]
智能家居这块你们提供的是整套IOT方案不是吗？
从一个SDK用户的视角难道还要去区分是webbridge的问题还是web开发的问题？
我们是SDK的用户，不是SDK的测试人员啊

**Comment by littleGauze** [comment]
touchDown() 没有成功阻止tab切换 在切换后才执行touchDown 导致没有成对出现，我会在touchDown 之后无论如何调用一次touchUp
