### ISSUE TITLE
长链接重连机制和用户登录状态相关性的疑问

### ISSUE THREAD

**Issue by weipinglii** [Rokid/RokidMobileSDKiOSDemo#12]
场景：
1. 非登录状态启动app：
登录成功后进入主页面，通常情况下device.alive = 0，无法收到长链接推送
此时杀进程重启app，大概率长链接恢复正常，device.alive = 1
2. 登录状态启动app：
  1. 大概率长链接正常，device.alive = 1
  2. 小概率长链接不正常，同样杀进程重启app之后大概率恢复正常，device.alive = 1

推测：
- 怀疑长链接是否正常工作和用户登录状态强相关
- 怀疑用户登录成功之后，没有重试长链接的机制

**Comment by shper** [comment]
这个问题 已经修复，请更新 SDK
