### ISSUE TITLE
长按禁麦键将设备恢复出厂设置或者设备被其他账号绑定后（实际上已经是解绑的状态）但是没有收到设备列表变更的通知

### ISSUE THREAD

**Issue by weipinglii** [Rokid/RokidMobileSDKiOSDemo#13]
> 1）app端账户和音箱设备绑定，音箱端长按禁麦键5秒，恢复出厂设置
> 
> 期待结果：
> 1）app端账户和音箱端绑定关系解除
> 
> 实际结果：
> 1）关系没有解除
> 
> 相同的case，安卓客户端是可以解除的
> 

以上是测试给我提的bug，调试发现从设备端解绑后只会收到`RokidSDK.RKDeviceOnlineStatus.offline`这个通知，但是实际上设备是已经解绑的状态

按照逻辑SDK应该要发出设备列表变更的通知`RKNotificationName.DeviceListUpdated`

**Comment by weipinglii** [comment]
设备被其他用户绑定也是类似的情况，不会收到设备列表变更的通知

**Comment by weipinglii** [comment]
补充说明：
现在我的处理在`resetDeviceWithDeviceId:`返回`YES`之后会马上请求`queryDeviceListWithCompletion`，确认设备是否在当前设备列表中。但是确认的结果经常是设备仍然在当前设备列表中。如果稍等一会儿再`queryDeviceListWithCompletion`请求当前设备列表就可以确认到设备已不在列表中。

从上述现象看，要解决这个问题：
1. SDK需要在所有设备绑定关系发生变化时发出`RKNotificationName.DeviceListUpdated`的通知。
2. 给`resetDeviceWithDeviceId:`提供一个`completionBlock`，用来提供app段发起设备列表确认请求。

建议双管齐下，1可以同时解决多个场景：
* 设备被别人绑定
* 长按设备禁麦键恢复出厂设置
* 从app里恢复出厂设置
* app端设备解绑
2 可以确保长链接不work的时候也可以在合适的时机通过主动请求设备列表触发`RKNotificationName.DeviceListUpdated`的通知

**Comment by shper** [comment]
消息已经添加。
