### ISSUE TITLE
调用updateLocationWithDeviceId:completion:更新设备地址后，从获取到的设备地址仍然是之前的地址

### ISSUE THREAD

**Issue by weipinglii** [Rokid/RokidMobileSDKiOSDemo#14]
如题，调用`updateLocationWithDeviceId:completion:`更新设备地址后，通过`getLocationWithDeviceId:completion:`或者`device.location`获取到的设备地址并不会更新，必须再次调用`queryDeviceListWithCompletion`获取设备列表成功之后，`device.locaiton`才会更新成设置的地址。

建议：
考虑在`updateLocationWithDeviceId:completion:`回调成功时，SDK直接更新本地设备的`device.location`信息

**Comment by zhglinux** [comment]
已更新sdk
