### ISSUE TITLE
崩溃 dyld: Symbol not found

### ISSUE THREAD

**Issue by anwent** [Rokid/RokidMobileSDKiOSDemo#15]
请问我根据教程 在项目中添加了 `RokidSDK.framework` 在`Embed Frameworks` 中添加了 也在 search path中设置了路径 运行后崩溃
![crash](https://user-images.githubusercontent.com/15354932/39342661-a0bf047a-4a0b-11e8-8275-b14bdf26c42f.png)

![2018-04-27 11 10 02](https://user-images.githubusercontent.com/15354932/39342676-a89467da-4a0b-11e8-9cd2-310ddfd0d5be.png)

请问这是什么问题 我要怎么解决 谢谢了！！！

**Comment by anwent** [comment]
![2018-04-27 11 11 45](https://user-images.githubusercontent.com/15354932/39342714-ce97e89e-4a0b-11e8-8d88-efd8af661a6b.png)

项目是Swift4.1

**Comment by anwent** [comment]
@shper

**Comment by zhglinux** [comment]
目前还不支持swift4.1, 请切换到3.2

**Comment by anwent** [comment]
切换了仍然crash 是我哪里配置的不对吗？

**Comment by anwent** [comment]
方便加个QQ交流一下吗？ 比较急。。。谢谢 229202783

**Comment by shper** [comment]
@anwent 请截图你 整个 工程的 目录结构，有可能是你路径设置错误了。

**Comment by anwent** [comment]
![2018-05-02 5 27 16](https://user-images.githubusercontent.com/15354932/39516115-87991b80-4e2e-11e8-816e-39a76ac33d65.png)

**Comment by anwent** [comment]
![2018-05-02 5 30 16](https://user-images.githubusercontent.com/15354932/39516125-93a77796-4e2e-11e8-92b7-e43a685dee8c.png)

**Comment by anwent** [comment]
项目用swift， 在 `AppDelegate` 中 `import RokidSDK` 或者在桥接的OC文件中 `@import RokidSDK;` 不会崩溃，但是一调用`[RokidMobileSDK shared] initSDKWithAppKey`就崩了。。

**Comment by anwent** [comment]
![2018-05-02 5 32 56](https://user-images.githubusercontent.com/15354932/39516225-e466c8c6-4e2e-11e8-8f2a-5279670af846.png)
@shper 求解答一下 搞了好久了没办法了。。

**Comment by anwent** [comment]
![2018-05-02 5 37 48](https://user-images.githubusercontent.com/15354932/39516439-8ebe0c76-4e2f-11e8-9262-cb3e66de0bde.png)

**Comment by weipinglii** [comment]
@anwent 建议检查一下你的workspace=>pods工程=> targets列表中=>每个swift pod库 => `build setting`=>`swift language version` 这一项是否和DEMO里面的设置一致

**Comment by anwent** [comment]
@weipinglii  可以了 十分感谢

**Comment by weipinglii** [comment]
@anwent 可以在`podfile`里面加上这一段，就不需要每次`pod install`的时候去手动选择版本了 

```
post_install do |installer|
    # 需要指定编译版本的第三方的名称
    myTargets1 = ['Starscream', 'SnapKit', 'ReachabilitySwift', 'ProtocolBuffers-Swift']
    myTargets2 = ['SQLite.swift']
    
    installer.pods_project.targets.each do |target|
        if myTargets1.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.3'
            end
        end
        if myTargets2.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        end
    end
end
```

**Comment by anwent** [comment]
谢谢
