### ISSUE TITLE
`asrCorrect`系列接口错误

### ISSUE THREAD

**Issue by weipinglii** [Rokid/RokidMobileSDKiOSDemo#16]
如题，访问`asrCorrect`系列接口返回错误
-
在DEMO中使用若琪账号通过`tempLoginWithName:password:complete`接口登录后可以正常访问`asrCorrect..`等接口

DEMO中切换成第三方的app信息，使用`tokenLoginWithUserId: token: completion`登录之后`asrCorrect..`系列的接口返回错误。

抓包响应显示`CheckToken() error`

**Comment by zhglinux** [comment]
sdk已更新
