### ISSUE TITLE
`pingDevice:completion:`的completionBlock回调多次

### ISSUE THREAD

**Issue by weipinglii** [Rokid/RokidMobileSDKiOSDemo#17]
建议只在确认完ping设备的结果之后回调一次
-
如题，`device.alive == YES`的时候调用接口，block只会回调一次，在传入的`device.alive == NO`的时候，block会回调两次；

 以设备恢复出厂设置为例，在调用`resetDeviceWithDeviceId:`之前，先通过`pingDevice:completion:`然后在`completion`中判断设备在线状况：
* 如果`device.alive == YES` 那么我继续调用`resetDeviceWithDeviceId:`接口
* 如果`device.alive == NO`那么弹窗提示用户设备不在线。

初始状态时`device.alive == NO`，block会有两次回调，分两种状况：
1. 两次`device.alive == NO` 导致连续弹窗
2. 首次`device.alive == NO`， 第二次`device.alive == YES`，弹窗提示设备不在线后，恢复出厂设置成功。

建议只在确认完ping设备的结果之后回调一次

**Comment by anwent** [comment]
兄弟 我在集成sdk时候遇到了问题 能加个qq请教一下吗  229202783

**Comment by zhglinux** [comment]
更新sdk
