### ISSUE TITLE
在没有网络的情况下，RKWebBridge没有页面加载失败的回调

### ISSUE THREAD

**Issue by weipinglii** [Rokid/RokidMobileSDKiOSDemo#20]
如题，现有的`errorViewWithState:retryUrl:` & `showToastWithMessage:` 等bridge的代理都没有回调，只显示空白页面。

建议增加一个代理方法，或者其他的方式，用来在没有网络时，app端来处理网络异常的提示

**Comment by shper** [comment]
你好，异常 兜底页面，请自行开发。谢谢。
