### ISSUE TITLE
IOT的页面在token失效的情况下请求错误，展示错误页面

### ISSUE THREAD

**Issue by weipinglii** [Rokid/RokidMobileSDKiOSDemo#21]
如题

页面的失败和点击页面的重试按钮之后并没有SDK的相应回调，app端无法知道是因为token失效或者其他错误引起的。
这个部分建议SDK处理一下，如果是token失效引起的就SDK发一个RKNotificationName.ShouldLogout的通知，让APP做对应的处理。如果是其他错误也需要有对应的回调进行错误的处理，比如 #20 描述的无网络加载失败的情况。

**Comment by shper** [comment]
目前 H5 和 Mobile SDK 没有这块交互。
